### PR TITLE
News : Gaffer 0.54 announcement

### PR DESCRIPTION
**Pull request by medubelko**
After many, many technical setbacks, here, finally, is the blog post announcing Gaffer 54.

@johnhaddon I've pushed this in an incomplete state, so you can look at the copy/videos/examples today (Thursday) and make comments. I expect to be able to fix any issues tomorrow and have it ready for you to merge on Friday. :crossed_fingers:

The Parent/Instancer/Seeds example was as bit rushed, but since it's only for this one announcement I don't mind that it's not up to the usual quality.

## To do ##
- [x] Make demo video file URLs detect OS (for Firefox/Safari compatibility).
- [x] Convert SetVisualiser demo to .webm.

### CODE REVIEW

**Comment by johnhaddon** [comment]
Thanks Michael - LGTM. My only questions are about the videos really. I couldn't get audio to play on the mp4s (tried on both Linux and Max) but could for the webms (again both platforms), and I'm not sure that having binary blobs that big in the repo is all that great. I wonder if we should be using the Cortex Vimeo channel to host them, thus perhaps solving both problems?

**Comment by medubelko** [comment]
Hmm, disappointing to hear the audio's not working. Probably because I used Opus for the .webms –it's much more recent than Vorbis and MPEG.

Vimeo's a good option. Once I rebase, did you want to vet the audio before merging?

**Comment by andrewkaufman** [comment]
We're about to release 0.54.0.2 (today hopefully, but if not overnight). Should we bump straight to that?

**Comment by medubelko** [comment]
I'm going to bump the post's date to tomorrow, so as long as the download link is available on GitHub, that should be fine.

**Comment by andrewkaufman** [comment]
Actually, I guess it might be 0.54.1.0 with a new Orientation node that should be in the announcement as well.

**Comment by medubelko** [comment]
Rebased. The Vimeo vids are public and the post links to them.

Daniel and I threw together an example for the Orientation node. Hopefully it doesn't need revision. If it does, the last 2 commits can be dropped, and we can talk about it in a separate post.

@johnhaddon This should be good to merge tomorrow.

**Comment by medubelko** [comment]
Goes without saying, but if 0.54.1.0 somehow doesn't get released tomorrow, we should drop those last 2 commits.

**Comment by johnhaddon** [comment]
Thanks - checked out the Vimeo vids and the audio is working for me on all of them. I've released 0.54.1.0 and the linux build and documentation is up, just trying to coax a mac build out of azure at present. If that doesn't work, I'll make one on my laptop instead. There are two invalid links being flagged by the Travis tests right now - one is just the mac build that hasn't been uploaded yet, and the other is because the documentation got shuffled around. Could you fix that second one?

**Comment by johnhaddon** [comment]
OK, I've got a mac build up now, so just this broken link remains :

```
External link http://gafferhq.org/documentation/0.54.1.0/Tutorials/BeginnerTutorial/index.html failed: 404 No error
```

Could you take care of that and then merge?

Thanks very much for putting this together - I have a tendency to slide releases out unannounced so it's great to have someone playing the trumpet.

**Pull request merged**
