### PR TITLE
Fix docker-based previews

### PR DESCRIPTION
**Pull request by johnhaddon**
The Gemfile was breaking them. I've also removed the instructions for previewing the site via `bundle exec` since that required the Gemfile.

@medubelko, hopefully this is OK with you now that you have Docker available?

### CODE REVIEW

**Comment by themissingcow** [comment]
@johnhaddon Oh, Travis uses the `Gemfile` for its tests. I'd previously made a version where it just removes `html-proofer` from `Gemfile` and manually installs it in `travis.yaml`. @medubelko said this wouldn't then work with his local build, but if the gist of this commit is that you might be able to use Docker now Michael, then that is less of an issue?

**Comment by johnhaddon** [comment]
Can you send me the right incantation for the `.travis.yml` and I'll update?

**Comment by themissingcow** [comment]
> Can you send me the right incantation for the `.travis.yml` and I'll update?

@johnhaddon see #47 - needed to test it on Travis...

**Comment by themissingcow** [comment]
Superseded by #47

**Pull request closed without merging**
