### PR TITLE
Imagery update

### PR DESCRIPTION
**Pull request by medubelko**
Updates to show and Gaffer imagery for Siggraph. I still plan to replace the carousel with static images, but this works as a stop-gap.

Preview by running `gafferHQServer` in `/home/michaeldu/dev/gafferHQBuilds/imageryUpdate`

Note: I'm including the Gaffer screenshots because I think it's more appropriate for OSS. Only the proprietary images should be hotlinked.

### Changes
- Added links to more recent shows
- Updated in-app screenshots
- Made darkening the carousel images optional
- Made adjusting the Y-axis of header and carousel images optional
- Shrunk the header

### CODE REVIEW

**Comment by andrewkaufman** [comment]
I like it in general (though I realize we're still planning to get rid of the carousel in the end). I really like the first pic from LIS.

Just a couple thoughts:

- The 2nd pic has a really complex shading graph coupled with a really trivial blue ball.... can we make that ball nicer somehow, to make it merit all that complexity?
- The deep canyon in pic 5 is very polygonal... can we find something better since this is our "gaffer is great for complexity" pic?
- The robot render is pretty artifact-ed. Is that just the jpg compression? Or did we not get a clean render in the first place?
- All of the pics on the main page are TV... that's a shame, as it could be seen to say 'Gaffer isn't good enough for film'. Logan is pretty impressive though... can we put that (or similar) on the main page?

**Comment by medubelko** [comment]
1. Blue ball: Ideally, I would have liked to include an asset, but that would require additional clearance. Of the show scripts I looked at, most shaders were similarly simple. Any suggestions for a fancier one?
2. Canyon: Options for recent shows are the [final result of that shot](http://saq4c3yiajw43pk4q158d9l3.wpengine.netdna-cdn.com/wp-content/uploads/2018/04/102_002_110_final.1170.jpg), or the [robot attack scene in greyshade](http://image-engine.com/wp-content/uploads/2018/04/101_040_600_AO.1006.jpg).
3. Daniel helped me reduce the artifacting, but the IPR seemed to only take it so far. We can look at it together, if you have time.
4. The only reason Logan isn't on the front page is that it was the only new image that came close to working when put behind a 300px tall frame. The shorter header images limit our possibilities that way.

**Comment by medubelko** [comment]
Updated Gaffy render, replaced shaderball with Gaffy, replaced LIS ship with forest attack alien, added new Logan shot to carousel.

**Comment by andrewkaufman** [comment]
Thanks!

**Pull request merged**
