### PR TITLE
Update "Blog"/"Demos"

### PR DESCRIPTION
**Pull request by medubelko**
Content, style, and structure updates for "Blog"/"Demos".

All blog posts, presentations, papers, demo videos, and tips of the day have been moved to a generic "News" section. If at a later point we split off Documentation to a "Learn" section, the demo vids will be moved there.

Preview at: `/home/michaeldu/dev/gafferHQBuilds/newsUpdate`

### CODE REVIEW

**Comment by andrewkaufman** [comment]
I like it, but we seem to have lost the most recent demo videos in the process. Was that intentional?

**Comment by medubelko** [comment]
It was moved to the Download page, and is a core component of it. Want it as a post, too?

**Comment by andrewkaufman** [comment]
> Want it as a post, too?

Yes please

**Comment by medubelko** [comment]
Incorporated Andrew's request and rebased.

**Pull request merged**
