### PR TITLE
Update header.html

### PR DESCRIPTION
**Pull request by medubelko**
Style and logo update for header.html

The goal is to prevent the navbar from morphing between different sizes, make it more readable, and add a more navbar-appropriate version of the logo.

For the adjusted logo, I didn't think the "G" would suffice. If you think the adjustment will negatively affect the brand, let me know.

Preview at: `/home/michaeldu/dev/gafferHQBuilds/headerUpdate`

### CODE REVIEW

**Comment by andrewkaufman** [comment]
needs a rebase

**Comment by medubelko** [comment]
Something messed up with an earlier rebase, so I had to remove the Forum entry again. Made a slight aesthetic change to the navbar (no more transparency), and rebased.

**Comment by andrewkaufman** [comment]
I probably should have made this comment before merging, but should we embedd the github page into an iframe like we do for community? Otherwise we've just left the site on the 3rd click...

**Comment by medubelko** [comment]
I glanced around at other sites to double-check, and it seems fairly consistent that OSS sites are sending people off to GitHub through the nav.

In any case, iframing a whole site isn't ideal. Certain of their pages (gists, for instance) have `X-Frame-Options: deny`, which specifically blocks iframing.

**Comment by andrewkaufman** [comment]
Ok, lets leave it then

**Pull request merged**
