### PR TITLE
CI : Remove `htmlproofer --check-html` option

### PR DESCRIPTION
**Pull request by johnhaddon**
This feature was removed in `htmlproofer` 4.0. From the developer :

> This was intentionally removed as part of the html-proofer 4.0 major release. It was removed because, over the years, it has provided more false positives than actual errors. HTML 5 engines in particular are much more forgiving of broken HTML, and so it logging the four or five small errors this check actual looked for was not worth the trouble of maintainence (I'm just one developer). I know of no other tools which duplicate the feature but there might be some W3C validators which run a similar check.

We are much more interested in the link and image validation features, which continue to work.

### CODE REVIEW

**Comment by johnhaddon** [comment]
This gets `htmlproofer` running again by updating to the argument format required by `4.0`. But `4.0` has a bunch of default checks that the old version didn't have, so I think now we need to actually go and fix a bunch of the HTML. Parking this for now - will revisit when I have more time.

**Review by murraystevenson — APPROVED** [review]
This seems reasonable enough to me, it's a bit of a shame to break existing links to news postings but they'd all be a few years out of date by this point.

I prematurely updated the Arnold and OSL links in #123 but can revisit that once this is merged.

**Comment by johnhaddon** [comment]
> it's a bit of a shame to break existing links to news postings but they'd all be a few years out of date by this point.

Oh, I hadn't considered that - since they weren't linked to from the home page any more, I assumed they were irrelevant, but as you say they could have external links pointing at them still. I could fix up all the bad links in the posts instead if you think it's worth it (although I'm not sure I want to be tied to Jekyll forever just to keep them working in posterity).

**Comment by johnhaddon** [comment]
> Doesn't quite remove the overhead of generating the news posts, but we could replace their content with a redirect to the equivalent blog post?

Oh, neat! I've dropped the commit that removed them and cherry-picked your commit. Let's see what CI says now. I still think I'd like to drop this completely at some point so we can move on from Jekyll, but this seems like a neat way of keeping them alive a bit longer...

**Pull request merged**
